import React from 'react'

interface LivePreviewProps {
  themeId: string
  images: string[]
  albumTitle?: string
}

const LivePreview: React.FC<LivePreviewProps> = ({ themeId, images, albumTitle = 'My Photography Album' }) => {
  const isDark = themeId === 'dark'
  const isVibrant = themeId === 'vibrant'

  return (
    <div 
      className={`
        w-full h-[400px] border rounded-lg overflow-hidden shadow-inner flex flex-col transition-colors duration-500
        ${isDark ? 'bg-gray-900 text-white border-gray-800' : isVibrant ? 'bg-orange-50 text-gray-900 border-orange-200' : 'bg-white text-gray-900 border-gray-200'}
      `}
    >
      {/* Mini Header */}
      <div className={`p-4 border-b ${isDark ? 'border-gray-800' : isVibrant ? 'border-orange-100' : 'border-gray-100'}`}>
        <h4 className="text-sm font-bold uppercase tracking-widest">{albumTitle}</h4>
      </div>

      {/* Mini Gallery Content */}
      <div className="flex-1 p-6 overflow-y-auto">
        <div className="grid grid-cols-2 gap-4">
          {images.length > 0 ? (
            images.map((img, i) => (
              <div 
                key={i} 
                className={`aspect-square rounded overflow-hidden shadow-sm flex items-center justify-center text-xs font-medium border
                  ${isDark ? 'bg-gray-800 border-gray-700 text-gray-400' : isVibrant ? 'bg-orange-100 border-orange-200 text-orange-600' : 'bg-gray-50 border-gray-100 text-gray-500'}
                `}
              >
                <img 
                  src={img} 
                  alt={`Album Image ${i + 1}`} 
                  className="w-full h-full object-cover"
                />
              </div>
            ))
          ) : (
            <div className="col-span-2 h-40 flex items-center justify-center border-2 border-dashed border-gray-300 rounded text-gray-400 italic">
              No images uploaded yet
            </div>
          )}
        </div>
        
        {/* Sample text block */}
        <div className="mt-8 space-y-2">
          <div className={`h-2 w-3/4 rounded ${isDark ? 'bg-gray-800' : 'bg-gray-100'}`} />
          <div className={`h-2 w-1/2 rounded ${isDark ? 'bg-gray-800' : 'bg-gray-100'}`} />
        </div>
      </div>
      
      {/* Mini Footer */}
      <div className={`p-3 text-[10px] text-center ${isDark ? 'text-gray-600' : 'text-gray-400'}`}>
        Generated by Omni-Channel
      </div>
    </div>
  )
}

export default LivePreview
